### ISSUE TITLE
Numbered items appearing out-of-order when sorted by name

### ISSUE THREAD

**Issue by JamesDBartlett** [NidalShater/Bertelsmann-Scholarship-Udacity-Challenge-Deep-Learning-Course-Summary#1]
The numbering of the filenames is causing them to be sorted out-of-order. 
![image](https://user-images.githubusercontent.com/37491308/73608802-dd5fc300-458c-11ea-9415-905be2d168d6.png)
You can solve this problem by left-padding all numbers with as many zeros as it takes to make them the same length as the largest number in the set. So, for a set of 99 items or fewer, you can correct the problem by adding a single leading zero on all single-digit numbers, like so:
01 - perceptron.jpg
02 - perceptron.jpg
03 - perceptron.jpg
and so on...

Here's a bit of code that calculates how many leading zeros you'll need on the smallest number:
![image](https://user-images.githubusercontent.com/37491308/73609657-988c5a00-4595-11ea-80fc-69c3151347b8.png)
https://colab.research.google.com/drive/1XFHdbhK3IJeJHR1ni7UtvZipG4fNgn1Z

**Comment by NidalShater** [comment]
Thanks a lot for this note, it didn't show up locally but here in GitHub, fix it and thanks for sharing this cool numpy code as well
